#!/usr/bin/env python3
"""
Publish Kiro-generated Markdown docs to Confluence Cloud.

Usage:
    python scripts/publish_to_confluence.py --docs-dir docs/generated
    python scripts/publish_to_confluence.py --docs-dir docs/generated --dry-run
    python scripts/publish_to_confluence.py --docs-dir docs/generated --parent-page-title "RoadIQ Documentation"
"""

import argparse
import os
import re
import sys
from datetime import datetime, timezone
from pathlib import Path

import requests
from dotenv import load_dotenv

load_dotenv()

CONFLUENCE_URL = os.environ.get("CONFLUENCE_URL", "").rstrip("/")
CONFLUENCE_EMAIL = os.environ.get("CONFLUENCE_EMAIL", "")
CONFLUENCE_API_TOKEN = os.environ.get("CONFLUENCE_API_TOKEN", "")
CONFLUENCE_SPACE_KEY = os.environ.get("CONFLUENCE_SPACE_KEY", "")


def check_env():
    missing = [
        name for name, val in {
            "CONFLUENCE_URL": CONFLUENCE_URL,
            "CONFLUENCE_EMAIL": CONFLUENCE_EMAIL,
            "CONFLUENCE_API_TOKEN": CONFLUENCE_API_TOKEN,
            "CONFLUENCE_SPACE_KEY": CONFLUENCE_SPACE_KEY,
        }.items() if not val
    ]
    if missing:
        print(f"ERROR: Missing required environment variables: {', '.join(missing)}", file=sys.stderr)
        print("Copy .env.example to .env and fill in your credentials.", file=sys.stderr)
        sys.exit(1)


def get_auth():
    return (CONFLUENCE_EMAIL, CONFLUENCE_API_TOKEN)


def markdown_to_confluence_storage(markdown_text: str) -> str:
    text = markdown_text

    # Strip auto-generated comment header
    text = re.sub(r"^<!--.*?-->\n?", "", text, flags=re.DOTALL)

    # Headings
    text = re.sub(r"^#### (.+)$", r"<h4>\1</h4>", text, flags=re.MULTILINE)
    text = re.sub(r"^### (.+)$", r"<h3>\1</h3>", text, flags=re.MULTILINE)
    text = re.sub(r"^## (.+)$", r"<h2>\1</h2>", text, flags=re.MULTILINE)
    text = re.sub(r"^# (.+)$", r"<h1>\1</h1>", text, flags=re.MULTILINE)

    # Code blocks with language
    text = re.sub(
        r"```(\w+)\n(.*?)```",
        r'<ac:structured-macro ac:name="code"><ac:parameter ac:name="language">\1</ac:parameter>'
        r"<ac:plain-text-body><![CDATA[\2]]></ac:plain-text-body></ac:structured-macro>",
        text, flags=re.DOTALL,
    )
    # Code blocks without language
    text = re.sub(
        r"```\n(.*?)```",
        r'<ac:structured-macro ac:name="code"><ac:plain-text-body><![CDATA[\1]]></ac:plain-text-body></ac:structured-macro>',
        text, flags=re.DOTALL,
    )

    # Inline code
    text = re.sub(r"`([^`]+)`", r"<code>\1</code>", text)

    # Bold and italic
    text = re.sub(r"\*\*(.+?)\*\*", r"<strong>\1</strong>", text)
    text = re.sub(r"\*(.+?)\*", r"<em>\1</em>", text)

    # Tables
    def convert_table(match):
        lines = [l.strip() for l in match.group(0).strip().split("\n") if l.strip()]
        rows = [l for l in lines if not re.match(r"^\|[-| :]+\|$", l)]
        if not rows:
            return match.group(0)
        result = ["<table>"]
        for i, row in enumerate(rows):
            cells = [c.strip() for c in row.strip("|").split("|")]
            tag = "th" if i == 0 else "td"
            result.append("<tr>" + "".join(f"<{tag}>{c}</{tag}>" for c in cells) + "</tr>")
        result.append("</table>")
        return "\n".join(result)

    text = re.sub(r"(\|.+\|\n)+", convert_table, text)

    # Unordered lists
    lines = text.split("\n")
    output, in_list = [], False
    for line in lines:
        if re.match(r"^[-*] ", line):
            if not in_list:
                output.append("<ul>")
                in_list = True
            output.append(f"<li>{line[2:]}</li>")
        else:
            if in_list:
                output.append("</ul>")
                in_list = False
            output.append(line)
    if in_list:
        output.append("</ul>")
    text = "\n".join(output)

    # Paragraphs
    paragraphs = re.split(r"\n{2,}", text)
    result = []
    for p in paragraphs:
        p = p.strip()
        if not p:
            continue
        if p.startswith("<"):
            result.append(p)
        else:
            result.append(f"<p>{p}</p>")
    return "\n".join(result)


def build_banner(source_file: str) -> str:
    now = datetime.now(timezone.utc).strftime("%Y-%m-%d %H:%M UTC")
    return (
        f'<ac:structured-macro ac:name="info">'
        f"<ac:rich-text-body>"
        f"<p>Auto-generated by Kiro | Source: <code>{source_file}</code> | Updated: {now}</p>"
        f"</ac:rich-text-body>"
        f"</ac:structured-macro>\n"
    )


def get_page_by_title(title: str, space_key: str) -> dict | None:
    url = f"{CONFLUENCE_URL}/wiki/rest/api/content"
    params = {"title": title, "spaceKey": space_key, "expand": "version"}
    resp = requests.get(url, params=params, auth=get_auth())
    resp.raise_for_status()
    results = resp.json().get("results", [])
    return results[0] if results else None


def get_page_id_by_title(title: str, space_key: str) -> str | None:
    page = get_page_by_title(title, space_key)
    return page["id"] if page else None


def create_page(title: str, body: str, space_key: str, parent_id: str | None = None) -> dict:
    url = f"{CONFLUENCE_URL}/wiki/rest/api/content"
    payload = {
        "type": "page",
        "title": title,
        "space": {"key": space_key},
        "body": {"storage": {"value": body, "representation": "storage"}},
    }
    if parent_id:
        payload["ancestors"] = [{"id": parent_id}]
    resp = requests.post(url, json=payload, auth=get_auth())
    resp.raise_for_status()
    return resp.json()


def update_page(page_id: str, title: str, body: str, current_version: int) -> dict:
    url = f"{CONFLUENCE_URL}/wiki/rest/api/content/{page_id}"
    payload = {
        "type": "page",
        "title": title,
        "version": {"number": current_version + 1},
        "body": {"storage": {"value": body, "representation": "storage"}},
    }
    resp = requests.put(url, json=payload, auth=get_auth())
    resp.raise_for_status()
    return resp.json()


def derive_page_title(md_file: Path) -> str:
    text = md_file.read_text(encoding="utf-8")
    match = re.search(r"^# (.+)$", text, re.MULTILINE)
    if match:
        return match.group(1).strip()
    return md_file.stem.replace("-", " ").replace("_", " ").title()


def publish_file(md_file: Path, parent_id: str | None, dry_run: bool) -> bool:
    title = derive_page_title(md_file)
    raw_markdown = md_file.read_text(encoding="utf-8")
    storage_body = build_banner(md_file.name) + markdown_to_confluence_storage(raw_markdown)

    existing = get_page_by_title(title, CONFLUENCE_SPACE_KEY)

    if dry_run:
        action = "UPDATE" if existing else "CREATE"
        print(f"  [DRY RUN] {action}: '{title}' (from {md_file.name})")
        return True

    try:
        if existing:
            version = existing["version"]["number"]
            update_page(existing["id"], title, storage_body, version)
            page_url = f"{CONFLUENCE_URL}/wiki{existing['_links']['webui']}" if "_links" in existing else ""
            print(f"  UPDATED: '{title}' {page_url}")
        else:
            result = create_page(title, storage_body, CONFLUENCE_SPACE_KEY, parent_id)
            page_url = f"{CONFLUENCE_URL}/wiki{result['_links']['webui']}"
            print(f"  CREATED: '{title}' {page_url}")
        return True
    except requests.HTTPError as e:
        print(f"  ERROR publishing '{title}': {e.response.status_code} {e.response.text}", file=sys.stderr)
        return False


def main():
    parser = argparse.ArgumentParser(description="Publish Kiro-generated docs to Confluence Cloud")
    parser.add_argument("--docs-dir", required=True, help="Directory containing generated .md files")
    parser.add_argument("--parent-page-title", default=None, help="Title of the Confluence parent page")
    parser.add_argument("--dry-run", action="store_true", help="Preview what would be published without making changes")
    args = parser.parse_args()

    if not args.dry_run:
        check_env()

    docs_dir = Path(args.docs_dir)
    if not docs_dir.exists():
        print(f"ERROR: docs directory not found: {docs_dir}", file=sys.stderr)
        sys.exit(1)

    md_files = list(docs_dir.glob("*.md"))
    if not md_files:
        print(f"No .md files found in {docs_dir}")
        sys.exit(0)

    parent_id = None
    if args.parent_page_title and not args.dry_run:
        parent_id = get_page_id_by_title(args.parent_page_title, CONFLUENCE_SPACE_KEY)
        if not parent_id:
            print(f"WARNING: Parent page '{args.parent_page_title}' not found — pages will be created at space root.")

    print(f"Publishing {len(md_files)} file(s) from {docs_dir}/ to Confluence space '{CONFLUENCE_SPACE_KEY}'")
    if args.dry_run:
        print("(DRY RUN — no changes will be made)\n")

    failures = 0
    for md_file in sorted(md_files):
        success = publish_file(md_file, parent_id, args.dry_run)
        if not success:
            failures += 1

    print(f"\nDone. {len(md_files) - failures}/{len(md_files)} published successfully.")
    if failures:
        sys.exit(1)


if __name__ == "__main__":
    main()
